permissions:
  contents: read

name: "HANA Docker Builder [PROD]"

on:
  push:
    branches:
      - main

jobs:
  runpod_awq_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cleanup Unused Docker Images
        run: docker rmi $(docker images -q) || true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: nicklas373
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build Runpod Docker Image for AWQ Quantize
        run: |
          docker build \
            -t nicklas373/hana-runpod-awq:1.1.3-PROD \
            -f runpod-awq.dockerfile \
            .
          mkdir -p runpod_image
          docker save -o runpod_image/runpod_image.tar nicklas373/hana-runpod-awq:1.1.3-PROD

      - name: Load Docker Images
        run: docker load -i runpod_image/runpod_image.tar

      - name: Deploy Docker Image to Docker Hub
        run: docker push nicklas373/hana-runpod-awq:1.1.3-PROD
